#include <stdio.h>
#include  <conio.h>
void main()
{
int a,b,c;
printf("enter three numbers: ");
scanf("%d%d%d" ,&a,&b,&c);
//finding largest
if(a>=b && a>=c)
{
printf("largest =%d\n",a);
}
else if (b>=a && b>=c)
{
printf("largest=%d\n",b);
}
else
{
printf("largest=%d\n",c);
}
//finding smallest
if(a<=b && a<=c)
printf("smallest =%d\n" ,a);
else if (b<=a && b<=c)
printf("smallest =%d\n" ,b);
else
printf("smallest =%d\n" ,c);
}